@echo off
REM TP5 — Tomcat embarqué (après mvn package)
REM Connexion DB : définir DB_URL, DB_USER, DB_PASSWORD (ex. Render ou PostgreSQL local)
REM set DB_URL=jdbc:postgresql://...
REM set DB_USER=...
REM set DB_PASSWORD=...
cd /d "%~dp0"
echo Lancement sur http://localhost:6060/gameverseacademy/
call mvn -q exec:java
