/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-04-19 17:09:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ma.ac.esi.gameverseacademy.model.Client;
import ma.ac.esi.gameverseacademy.model.User;

public final class clients_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Client");
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  @SuppressWarnings("unchecked")
  List<Client> clients = (List<Client>) request.getAttribute("clients");
  if (clients == null) {
    clients = java.util.Collections.emptyList();
  }
  User currentUser = (User) session.getAttribute("user");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>GameVerse Academy — Clients</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body { font-family: Arial, sans-serif; background: #1A1A2E; color: #fff; margin: 0; }\r\n");
      out.write("    .topbar {\r\n");
      out.write("      display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 12px;\r\n");
      out.write("      padding: 14px 20px; background: #16213e; border-bottom: 1px solid #2a3f5f;\r\n");
      out.write("    }\r\n");
      out.write("    .user-info { display: flex; align-items: center; gap: 10px; color: #cdd6f4; font-size: 15px; }\r\n");
      out.write("    .user-info i { font-size: 1.5rem; color: #4A90D9; }\r\n");
      out.write("    .logout-btn {\r\n");
      out.write("      display: inline-flex; align-items: center; gap: 8px;\r\n");
      out.write("      padding: 8px 16px; background: #e94560; color: #fff; border: none; border-radius: 8px;\r\n");
      out.write("      cursor: pointer; font-size: 14px; font-family: inherit;\r\n");
      out.write("    }\r\n");
      out.write("    .logout-btn:hover { filter: brightness(1.08); }\r\n");
      out.write("    .container { max-width: 1200px; margin: 40px auto; padding: 0 20px; }\r\n");
      out.write("    h1 { color: #4A90D9; }\r\n");
      out.write("    .meta { color: #aaa; font-size: 0.95rem; margin-bottom: 24px; }\r\n");
      out.write("    table { width: 100%; border-collapse: collapse; background: #fff; color: #333; border-radius: 8px; overflow: hidden; }\r\n");
      out.write("    th { background: #1E3A5F; color: white; padding: 12px; text-align: left; }\r\n");
      out.write("    td { padding: 10px 12px; border-bottom: 1px solid #ddd; vertical-align: middle; }\r\n");
      out.write("    tr:nth-child(even) { background: #EEF4FB; }\r\n");
      out.write("    tr:hover { background: #D6E8F7; }\r\n");
      out.write("    .nav { margin-top: 24px; }\r\n");
      out.write("    .nav a { color: #4A90D9; }\r\n");
      out.write("    .empty { color: #ccc; padding: 20px 0; }\r\n");
      out.write("    .role-badge { font-size: 12px; color: #889; margin-left: 6px; }\r\n");
      out.write("    .btn {\r\n");
      out.write("      display: inline-flex; align-items: center; gap: 6px;\r\n");
      out.write("      padding: 6px 12px; border-radius: 6px; border: none; cursor: pointer;\r\n");
      out.write("      font-size: 13px; font-family: inherit; text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-primary { background: #4A90D9; color: #fff; }\r\n");
      out.write("    .btn-primary:hover { filter: brightness(1.08); }\r\n");
      out.write("    .btn-edit { background: #f0ad4e; color: #fff; }\r\n");
      out.write("    .btn-edit:hover { filter: brightness(1.08); }\r\n");
      out.write("    .btn-delete { background: #e94560; color: #fff; }\r\n");
      out.write("    .btn-delete:hover { filter: brightness(1.08); }\r\n");
      out.write("    .actions { display: flex; gap: 6px; }\r\n");
      out.write("    .add-bar { margin-bottom: 16px; }\r\n");
      out.write("    .badge {\r\n");
      out.write("      display: inline-block; padding: 3px 8px; border-radius: 10px; font-size: 12px; font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .badge-FREE    { background: #e0e0e0; color: #333; }\r\n");
      out.write("    .badge-PREMIUM { background: #4A90D9; color: #fff; }\r\n");
      out.write("    .badge-VIP     { background: #f0ad4e; color: #fff; }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"topbar\">\r\n");
      out.write("    <div class=\"user-info\">\r\n");
      out.write("      <i class=\"bi bi-person-circle\" aria-hidden=\"true\"></i>\r\n");
      out.write("      <span>\r\n");
      out.write("        ");
      out.print( currentUser != null ? currentUser.getEmail() : "Visiteur" );
      out.write("\r\n");
      out.write("        ");
 if (currentUser != null) { 
      out.write("\r\n");
      out.write("          <span class=\"role-badge\">(");
      out.print( currentUser.getRole() );
      out.write(")</span>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/LogoutController\" method=\"post\">\r\n");
      out.write("      <button type=\"submit\" class=\"logout-btn\">\r\n");
      out.write("        <i class=\"bi bi-box-arrow-right\" aria-hidden=\"true\"></i> Déconnexion\r\n");
      out.write("      </button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h1>Gestion des clients</h1>\r\n");
      out.write("    <p class=\"meta\">Liste des clients inscrits à GameVerse Academy.</p>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (currentUser != null && currentUser.isAdmin()) { 
      out.write("\r\n");
      out.write("      <div class=\"add-bar\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ClientAddController\" class=\"btn btn-primary\">\r\n");
      out.write("          <i class=\"bi bi-plus-circle\"></i> Ajouter un client\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (clients.isEmpty()) { 
      out.write("\r\n");
      out.write("      <p class=\"empty\">Aucun client à afficher pour le moment.</p>\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("      <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th>ID</th>\r\n");
      out.write("            <th>Prénom</th>\r\n");
      out.write("            <th>Nom</th>\r\n");
      out.write("            <th>Email</th>\r\n");
      out.write("            <th>Téléphone</th>\r\n");
      out.write("            <th>Ville</th>\r\n");
      out.write("            <th>Abonnement</th>\r\n");
      out.write("            ");
 if (currentUser != null && currentUser.isAdmin()) { 
      out.write("\r\n");
      out.write("              <th>Actions</th>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("          </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("          ");
 for (Client c : clients) {
               String sub = c.getSubscriptionType() == null ? "FREE" : c.getSubscriptionType();
          
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>");
      out.print( c.getId() );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( c.getFirstName() == null ? "" : c.getFirstName() );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( c.getLastName()  == null ? "" : c.getLastName()  );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( c.getEmail()     == null ? "" : c.getEmail()     );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( c.getPhone()     == null ? "" : c.getPhone()     );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( c.getCity()      == null ? "" : c.getCity()      );
      out.write("</td>\r\n");
      out.write("              <td><span class=\"badge badge-");
      out.print( sub );
      out.write('"');
      out.write('>');
      out.print( sub );
      out.write("</span></td>\r\n");
      out.write("              ");
 if (currentUser != null && currentUser.isAdmin()) { 
      out.write("\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"actions\">\r\n");
      out.write("                    <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ClientEditController?id=");
      out.print( c.getId() );
      out.write("\" class=\"btn btn-edit\">\r\n");
      out.write("                      <i class=\"bi bi-pencil\"></i> Modifier\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/ClientDeleteController\" method=\"post\"\r\n");
      out.write("                          onsubmit=\"return confirm('Supprimer le client ");
      out.print( c.getFirstName() );
      out.write(' ');
      out.print( c.getLastName() );
      out.write(" ?');\"\r\n");
      out.write("                          style=\"display:inline;\">\r\n");
      out.write("                      <input type=\"hidden\" name=\"id\" value=\"");
      out.print( c.getId() );
      out.write("\">\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-delete\">\r\n");
      out.write("                        <i class=\"bi bi-trash\"></i> Supprimer\r\n");
      out.write("                      </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("              ");
 } 
      out.write("\r\n");
      out.write("            </tr>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <p class=\"nav\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home.html\">← Retour à l'accueil</a></p>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
