/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-04-19 17:11:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import ma.ac.esi.gameverseacademy.model.Client;
import ma.ac.esi.gameverseacademy.model.User;

public final class client_002dform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Client");
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  String formMode = (String) request.getAttribute("formMode");
  if (formMode == null) formMode = "add";
  Client client = (Client) request.getAttribute("client");
  String errorMessage = (String) request.getAttribute("errorMessage");
  User currentUser = (User) session.getAttribute("user");

  boolean isEdit = "edit".equals(formMode);
  String title  = isEdit ? "Modifier un client" : "Ajouter un client";
  String action = isEdit
      ? request.getContextPath() + "/ClientEditController"
      : request.getContextPath() + "/ClientAddController";

  String vId        = (client != null) ? String.valueOf(client.getId()) : "";
  String vFirstName = (client != null && client.getFirstName() != null) ? client.getFirstName() : "";
  String vLastName  = (client != null && client.getLastName()  != null) ? client.getLastName()  : "";
  String vEmail     = (client != null && client.getEmail()     != null) ? client.getEmail()     : "";
  String vPhone     = (client != null && client.getPhone()     != null) ? client.getPhone()     : "";
  String vCity      = (client != null && client.getCity()      != null) ? client.getCity()      : "";
  String vSub       = (client != null && client.getSubscriptionType() != null) ? client.getSubscriptionType() : "FREE";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>GameVerse Academy — ");
      out.print( title );
      out.write("</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("    body { font-family: Arial, sans-serif; background: #1A1A2E; color: #fff; margin: 0; }\r\n");
      out.write("    .topbar {\r\n");
      out.write("      display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 12px;\r\n");
      out.write("      padding: 14px 20px; background: #16213e; border-bottom: 1px solid #2a3f5f;\r\n");
      out.write("    }\r\n");
      out.write("    .user-info { display: flex; align-items: center; gap: 10px; color: #cdd6f4; font-size: 15px; }\r\n");
      out.write("    .user-info i { font-size: 1.5rem; color: #4A90D9; }\r\n");
      out.write("    .logout-btn {\r\n");
      out.write("      display: inline-flex; align-items: center; gap: 8px;\r\n");
      out.write("      padding: 8px 16px; background: #e94560; color: #fff; border: none; border-radius: 8px;\r\n");
      out.write("      cursor: pointer; font-size: 14px; font-family: inherit;\r\n");
      out.write("    }\r\n");
      out.write("    .container { max-width: 700px; margin: 40px auto; padding: 0 20px; }\r\n");
      out.write("    h1 { color: #4A90D9; }\r\n");
      out.write("    .meta { color: #aaa; font-size: 0.95rem; margin-bottom: 24px; }\r\n");
      out.write("    .role-badge { font-size: 12px; color: #889; margin-left: 6px; }\r\n");
      out.write("    .nav { margin-top: 24px; }\r\n");
      out.write("    .nav a { color: #4A90D9; }\r\n");
      out.write("    .card { background: #fff; color: #333; border-radius: 8px; padding: 24px; }\r\n");
      out.write("    .form-group { margin-bottom: 16px; }\r\n");
      out.write("    label { display: block; font-weight: bold; margin-bottom: 6px; color: #1E3A5F; }\r\n");
      out.write("    input[type=\"text\"], input[type=\"email\"], select {\r\n");
      out.write("      width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 6px; font-size: 14px;\r\n");
      out.write("      font-family: inherit; box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    .required { color: #e94560; }\r\n");
      out.write("    .btn {\r\n");
      out.write("      display: inline-flex; align-items: center; gap: 6px;\r\n");
      out.write("      padding: 10px 18px; border-radius: 6px; border: none; cursor: pointer;\r\n");
      out.write("      font-size: 14px; font-family: inherit; text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    .btn-primary { background: #4A90D9; color: #fff; }\r\n");
      out.write("    .btn-cancel  { background: #888;    color: #fff; margin-left: 8px; }\r\n");
      out.write("    .error {\r\n");
      out.write("      background: #fdecea; color: #a4161a; border: 1px solid #f5c2c0;\r\n");
      out.write("      padding: 10px 14px; border-radius: 6px; margin-bottom: 16px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"topbar\">\r\n");
      out.write("    <div class=\"user-info\">\r\n");
      out.write("      <i class=\"bi bi-person-circle\" aria-hidden=\"true\"></i>\r\n");
      out.write("      <span>\r\n");
      out.write("        ");
      out.print( currentUser != null ? currentUser.getEmail() : "Visiteur" );
      out.write("\r\n");
      out.write("        ");
 if (currentUser != null) { 
      out.write("\r\n");
      out.write("          <span class=\"role-badge\">(");
      out.print( currentUser.getRole() );
      out.write(")</span>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/LogoutController\" method=\"post\">\r\n");
      out.write("      <button type=\"submit\" class=\"logout-btn\">\r\n");
      out.write("        <i class=\"bi bi-box-arrow-right\" aria-hidden=\"true\"></i> Déconnexion\r\n");
      out.write("      </button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h1>");
      out.print( title );
      out.write("</h1>\r\n");
      out.write("    <p class=\"meta\">Les champs marqués <span class=\"required\">*</span> sont obligatoires.</p>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (errorMessage != null) { 
      out.write("\r\n");
      out.write("      <div class=\"error\">");
      out.print( errorMessage );
      out.write("</div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\">\r\n");
      out.write("      <form action=\"");
      out.print( action );
      out.write("\" method=\"post\">\r\n");
      out.write("        ");
 if (isEdit) { 
      out.write("\r\n");
      out.write("          <input type=\"hidden\" name=\"id\" value=\"");
      out.print( vId );
      out.write("\">\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <label>Prénom <span class=\"required\">*</span></label>\r\n");
      out.write("          <input type=\"text\" name=\"firstName\" value=\"");
      out.print( vFirstName );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <label>Nom <span class=\"required\">*</span></label>\r\n");
      out.write("          <input type=\"text\" name=\"lastName\" value=\"");
      out.print( vLastName );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <label>Email <span class=\"required\">*</span></label>\r\n");
      out.write("          <input type=\"email\" name=\"email\" value=\"");
      out.print( vEmail );
      out.write("\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <label>Téléphone</label>\r\n");
      out.write("          <input type=\"text\" name=\"phone\" value=\"");
      out.print( vPhone );
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <label>Ville</label>\r\n");
      out.write("          <input type=\"text\" name=\"city\" value=\"");
      out.print( vCity );
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"form-group\">\r\n");
      out.write("          <label>Type d'abonnement</label>\r\n");
      out.write("          <select name=\"subscriptionType\">\r\n");
      out.write("            <option value=\"FREE\"    ");
      out.print( "FREE".equals(vSub)    ? "selected" : "" );
      out.write(">FREE</option>\r\n");
      out.write("            <option value=\"PREMIUM\" ");
      out.print( "PREMIUM".equals(vSub) ? "selected" : "" );
      out.write(">PREMIUM</option>\r\n");
      out.write("            <option value=\"VIP\"     ");
      out.print( "VIP".equals(vSub)     ? "selected" : "" );
      out.write(">VIP</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("          <i class=\"bi bi-check-circle\"></i> ");
      out.print( isEdit ? "Enregistrer" : "Ajouter" );
      out.write("\r\n");
      out.write("        </button>\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/clients\" class=\"btn btn-cancel\">\r\n");
      out.write("          <i class=\"bi bi-x-circle\"></i> Annuler\r\n");
      out.write("        </a>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <p class=\"nav\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/clients\">← Retour à la liste</a></p>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
