/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.18
 * Generated at: 2026-04-23 18:04:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import ma.ac.esi.gameverseacademy.model.Mod;
import ma.ac.esi.gameverseacademy.model.User;

public final class mods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.Mod");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("ma.ac.esi.gameverseacademy.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  @SuppressWarnings("unchecked")
  List<Mod> mods = (List<Mod>) request.getAttribute("mods");
  if (mods == null) {
    mods = java.util.Collections.emptyList();
  }
  String filterCategory = (String) request.getAttribute("category");
  User currentUser = (User) session.getAttribute("user");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>GameVerse Academy — Mods</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/assets/css/gameverse-neon.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"topbar\">\r\n");
      out.write("    <div class=\"user-info\">\r\n");
      out.write("      <i class=\"bi bi-person-circle\" aria-hidden=\"true\"></i>\r\n");
      out.write("      <span>\r\n");
      out.write("        ");
      out.print( currentUser != null ? currentUser.getEmail() : "Visiteur" );
      out.write("\r\n");
      out.write("        ");
 if (currentUser != null) { 
      out.write("\r\n");
      out.write("          <span class=\"role-badge\">");
      out.print( currentUser.getRole() );
      out.write("</span>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <form action=\"");
      out.print( request.getContextPath() );
      out.write("/LogoutController\" method=\"post\">\r\n");
      out.write("      <button type=\"submit\" class=\"logout-btn\">\r\n");
      out.write("        <i class=\"bi bi-box-arrow-right\" aria-hidden=\"true\"></i> Déconnexion\r\n");
      out.write("      </button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h1>Mods</h1>\r\n");
      out.write("\r\n");
      out.write("    ");
 if (currentUser != null) { 
      out.write("\r\n");
      out.write("      <p class=\"meta\">\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/ModSubmitController\">\r\n");
      out.write("          <i class=\"bi bi-cloud-upload\"></i> Soumettre un mod\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 if (currentUser.isAdmin()) { 
      out.write("\r\n");
      out.write("          &nbsp;·&nbsp;\r\n");
      out.write("          <a href=\"");
      out.print( request.getContextPath() );
      out.write("/AdminController\">\r\n");
      out.write("            <i class=\"bi bi-shield-check\"></i> Modération (admin)\r\n");
      out.write("          </a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </p>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (filterCategory != null && !filterCategory.isBlank()) { 
      out.write("\r\n");
      out.write("      <p class=\"meta\">\r\n");
      out.write("        Filtre catégorie : <strong style=\"color:var(--neon-yellow);\">");
      out.print( filterCategory );
      out.write("</strong>\r\n");
      out.write("        &nbsp;·&nbsp;\r\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/mods\">Tout afficher</a>\r\n");
      out.write("      </p>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (mods.isEmpty()) { 
      out.write("\r\n");
      out.write("      <div class=\"empty\">Aucun mod à afficher pour le moment.</div>\r\n");
      out.write("    ");
 } else { 
      out.write("\r\n");
      out.write("      <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <th>ID</th>\r\n");
      out.write("            <th>Titre</th>\r\n");
      out.write("            <th>Catégorie</th>\r\n");
      out.write("            <th>Auteur</th>\r\n");
      out.write("            <th>Téléchargements</th>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("          ");
 for (Mod mod : mods) { 
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>");
      out.print( mod.getId() );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( mod.getTitle() == null ? "" : mod.getTitle() );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( mod.getCategory() == null ? "" : mod.getCategory() );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( mod.getAuthor() == null ? "" : mod.getAuthor() );
      out.write("</td>\r\n");
      out.write("              <td>");
      out.print( mod.getDownloads() );
      out.write("</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          ");
 } 
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("      </table>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <p class=\"nav\"><a href=\"");
      out.print( request.getContextPath() );
      out.write("/home.html\">← Retour à l'accueil</a></p>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
